### ISSUE TITLE
Orbiter v1.5 

### ISSUE THREAD

**Issue by jihunpark26** [KayosMaker/CANboard_Mounts#1]
The direction of rotation is not vertical
![Uploading 29FDD2B0-E2FA-4931-849A-98316C9B7963.jpeg…]()

**Comment by KayosMaker** [comment]
the orbiter plate is for orbiter 2.0
i am making a new one for orbiter 1.5
they have different motor rotation

**Comment by KayosMaker** [comment]
added files for orbiter 1.5, including cad
closing
