### ISSUE TITLE
Mount option for CW2?

### ISSUE THREAD

**Issue by ressu** [KayosMaker/CANboard_Mounts#10]
It seems that this repo comes highly recommended on many Voron community resources, but the one thing that is missing from the mounts is a mount for [Clockwork2](https://github.com/VoronDesign/Voron-Stealthburner). There is a slighly modified mount floating in Voron Discord that is modified from LGX lite.

Would it be possible to get CW2 versions of the mounts here too?

**Comment by KayosMaker** [comment]
I decided to leave it to Voron to develop mounts for the stock toolheads.  My mounts are primarily to help folks running non standard setups.
