### ISSUE TITLE
Mount option for Vz-Hextrudort-Low

### ISSUE THREAD

**Issue by ivanroberto** [KayosMaker/CANboard_Mounts#13]
Hello, it would be great if you had support for the Vz-Hextrudort-Low extruder.
[https://github.com/VzBoT3D/Vz-HextrudORT](url)
If any existing extruders are compatible, please let me know.
Thanks

**Comment by KayosMaker** [comment]
I'm looking at things today for the vz-hextrudort series.  I'll update the repo info when i know what works or have new stls to add.

**Comment by KayosMaker** [comment]
Im closing this issue for now.  Use the LGX Lite mount mirrored on X for the VZ HextrudORT Low extruders.  It's close enough to get you though til i can create perfect mounts for the VZ extruders.

**Comment by KayosMaker** [comment]
Not sure if this will notify you, but if it does, I've added native mounts for VZHextrudort now.
