### ISSUE TITLE
vzhextrudort_low_mounting_plate_strain_relief missing heatset inserts

### ISSUE THREAD

**Issue by Rye-3D** [KayosMaker/CANboard_Mounts#14]
SHT-36_and_BTT_EBB36_1.1_1.2_vzhextrudort_low_mounting_plate_strain_relief STL file is missing the heat set insert modifications on the bracket

**Comment by KayosMaker** [comment]
thanks ill look at that later today and push an update!

**Comment by claytono** [comment]
Looks like the Sherpa Micro strain relief STL is also missing heatset inserts

**Comment by KayosMaker** [comment]
just finished fixing all the missing heatset countersinks.  sorry bout that yall.  pushing update momentarily so closing this now
