### ISSUE TITLE
Sherpa crew mini support 

### ISSUE THREAD

**Issue by wight554** [KayosMaker/CANboard_Mounts#15]
Sherpa mount ~~might work~~ (edit. won't work), but would be great to separate mount with matching silhouette
https://github.com/jrlomas/Sherpa-Crew-Mini
Thanks for your work!

**Comment by KayosMaker** [comment]
That thing is pretty awesome, but I think i'll have to pass on including it in the lineup of mounts.  I just dont have time at present to work something up.  you could drop the sherpa crew cad into the step file from my repo and see if it lines up with any of the other extruders with diagonally oriented motors.  you might find one close enough to work.  you may need to mirror the bracket on X, but my parts are designed to be able to do that.  I hope you figure something out.  if you use my geometry to design a new bracket, post it in a usermod folder and ill approve the commit.  closing this issue.
