### ISSUE TITLE
Extruder from IdeaFormer Driect Drive Extruder

### ISSUE THREAD

**Issue by ItalikDev** [KayosMaker/CANboard_Mounts#17]
You can create mount for extruder:
https://grabcad.com/library/ideaformer-bde-extruder-1

Thank you.

**Comment by KayosMaker** [comment]
I took a look at the extruder in CAD.  I'm not very impressed, so I don't plan on making a dedicated mount.  It does a very poor job of restraining the filament path.  I'd recommend going with a Sherpa Mini, Sharkfin, or other BMG based extruder, if thats the path you want to go down.  
I did measure the motor angle of the Ideaformer BDE.  It does not perfectly align with any of my other mounts, but it is within 0.5 degrees of a mirrored Orbiter 1.5 mount.  If you mirror the Orbiter 1.5 mount on X, it will work with the Ideaformer extruder.   
Closing the issue now.  Thanks!
