### ISSUE TITLE
SHT-36 mount for Galileo

### ISSUE THREAD

**Issue by fuzzynm** [KayosMaker/CANboard_Mounts#3]
Would it be possible for you to model one up for the Galileo?  The SailFin is close but the motor mounts are off by a few degrees for the Galileo.

https://github.com/JaredC01/Galileo

**Comment by Tuerlich86** [comment]
Yes, that were very nice!!!

**Comment by KayosMaker** [comment]
REapola made one, its in a usermod folder now.
