### ISSUE TITLE
BTT EBB36 V1.1 & V1.2 support, works with SHT 36 mount

### ISSUE THREAD

**Issue by sneakytreesnake** [KayosMaker/CANboard_Mounts#6]
Tested the EBB36 V1.1 with the SHT36 mount and it works great! Worth clarifying in the mod description.

**Comment by brunnels** [comment]
Yes, seems okay.  Buttons are on the front now so button access on back no longer necessary.

**Comment by KayosMaker** [comment]
Thanks y'all.  Finally updating the repo now.
