### ISSUE TITLE
Input shaper orientations

### ISSUE THREAD

**Issue by CircuitSetup** [KayosMaker/CANboard_Mounts#7]
"Klipper does not to my knowledge currently support input shaper tuning in other orientations"

FYI, this can be done by using `axes_map` under [adxl345]. [See here.](https://www.klipper3d.org/Config_Reference.html#adxl345)

**Comment by AndyHegemann** [comment]
The axes_map does allow you to use an adxl345 in other orientations, but only ones that align its' axes with those of movement.

This doesn't let you mount the board to a sailfin or orbiter motor like with a sherpa mini. 

Here is the blurb explaining axes_map from the kilpper docs:

```
#axes_map: x, y, z
#   The accelerometer axis for each of the printer's X, Y, and Z axes.
#   This may be useful if the accelerometer is mounted in an
#   orientation that does not match the printer orientation. For
#   example, one could set this to "y, x, z" to swap the X and Y axes.
#   It is also possible to negate an axis if the accelerometer
#   direction is reversed (eg, "x, z, -y"). The default is "x, y, z".
```

**Comment by pottedplant** [comment]
`axes_map` would not help. Nonetheless the orientation does not matter for input shaper as it does not look at a specific axis from the sensor but takes the input from all 3 axis. So no need to align the axes in any way for IS to work properly.

https://github.com/Klipper3d/klipper/pull/5979#issuecomment-1379486909
